### ISSUE TITLE
Feature request: Option to center object

### ISSUE THREAD

**Issue by jlbrewer** [dairin0d/export-selected#1]
Dunno if this is being maintained but tossing an idea in anyway: In the export dialog options, what would make this tool pretty much perfect would be an option to center the exported selection to world space (0,0,0). I'm working from a composite file of several props to be individually exported for Unity and it would save the step of having to open the export and do it manually.

Granted, you can use the Append function in a blank file to similar effect, but the export selected automatically picks up the filename from the object which is another step saved. (Bonus credit: export as a linked file?)

**Comment by dairin0d** [comment]
Sorta maintained. I try to keep in mind the bug reports and feature requests, but I cannot predict when I get to fix/implement them.
What do you mean by "export as a linked file"?

**Comment by jlbrewer** [comment]
Works like the Link action (
https://cgcookie.com/blender/2010/07/12/tip-appending-and-linking/) but
initiated from the file you're exporting from. Totally unrelated to my
actual request though.

On Thu, Jun 11, 2015 at 2:33 AM, dairin0d notifications@github.com wrote:

> Sorta maintained. I try to keep in mind the bug reports and feature
> requests, but I cannot predict when I get to fix/implement them.
> What do you mean by "export as a linked file"?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dairin0d/export-selected/issues/1#issuecomment-111063741
> .

## 

---

Digital artist and dreamer of dreams
http://www.themindstream.net/mindstream

**Comment by dairin0d** [comment]
I added the "centering" option (see version 1.5.3).

As for "exporting as a linked file", I think you might want to check out my Cut/Copy/Paste addon (http://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/3D_interaction/CutCopyPaste3D). It has an option for "linked" object-pasting mode.
If you have further questions, you can contact me via blenderartists.org.
