### ISSUE TITLE
Not showing in the Addons list in 2.75

### ISSUE THREAD

**Issue by dilom** [dairin0d/export-selected#2]
This could be a problem with my installation, but when I select the addon to install from file it does not show anywhere in my addon list. I checked manually in Import/Export and also searching for "selected" or "export" does not show the addon. Any ideas? 
Thanks!

**Comment by dairin0d** [comment]
I have recently made a bugfix for Blender 2.78 which makes the script incompatible with the earlier versions. I can add handling for previous versions too, I just assumed everyone uses the latest one anyway.
Out of curiosity: why are you sticking with 2.75?

**Comment by dilom** [comment]
I need to make hardware changes to the system to update to the latest 
linux version and subsequently to update all the packages. Of course I 
could do manual install of several key programs but I might be stuck in 
some dependency nightmare. So far I have installed several popular and 
some niche addons and they seem to be compatible with the version I am 
using. I totally see why you can't support all legacy versions, but I 
guess it makes sense to have support going a year or two back just in 
case, unless it is very time consuming and counter productive.

**Comment by dairin0d** [comment]
Ok, I added some fixes to make it work in 2.75. Try using the latest commit.

**Comment by dilom** [comment]
Still not showing in the addon list. The log says it installed in the 
scripts directory and the file is there indeed.

**Comment by dairin0d** [comment]
Hm. Does it report any errors in the system console?

**Comment by dairin0d** [comment]
By the way, do any other addons in that directory show up in Blender?

**Comment by dilom** [comment]
Yeah the other addons in that directory work. Nothing appears in the 
console just green confirmation that it installed. The problem is that 
once I click "install from file" I don't see it in the addons list to 
enable it. I have enabled all supported levels and try searching for 
"export" and "export selected" and it doesn't come up. Tried clicking 
the Refresh button and still nothing.

**Comment by dairin0d** [comment]
Do I understand correctly that you were actually able to use some previous version of the addon? Or is this your first time installing it on your current system?

**Comment by dilom** [comment]
No this is the first time.

**Comment by dairin0d** [comment]
Can you look inside the other addons you have manually installed (and which you know to work)? There should be a
bl_info = {
line near the top of the file. Which version of Blender is mentioned there?

**Comment by dairin0d** [comment]
For the current Export Selected addon, this should be "blender": (2, 7, 0),.

**Comment by dilom** [comment]
Got it to work, the file I downloaded didn't override the old one I had 
initially. Just installed the latest version and it does work as it should!

Thanks for all the help!

**Comment by dairin0d** [comment]
You're welcome :-)
