### ISSUE TITLE
Does not work with Blender 2.79

### ISSUE THREAD

**Issue by EpicLPer** [dairin0d/export-selected#5]
This script sadly doesn't seem to work with 2.79 anymore, simply saying "Invalid Context Error" in a popup under the mouse and then does nothing.

**Comment by dairin0d** [comment]
Hm, I have blender 2.79, but I don't encounter errors with my addon. Was a newer version released? On blender.org, the download page shows the same (September 12, 2017) version as I have.
What operation were you trying to perform that resulted in "Invalid Context Error"? Did you install 2.79 just now? Did you use this addon with earlier Blender versions?

**Comment by sonygod** [comment]
not work 2.79b too.  2018-3-22

**Comment by dairin0d** [comment]
I downloaded 2.79b but still have no idea how to reproduce the problem. What does the error message in the system console say? (Window -> Toggle System Console)
At what point does the error happen? (I.e., when the addon is enabled, when the export dialogue is opened, when actual export is performed?) Does it depend on the specific format you try to export to?

**Comment by sonygod** [comment]
how to use in python script?
bpy.ops.export_scene.selected(exporter_str="export_scene.obj", use_file_browser=True)?

it's seem not work?

**Comment by dairin0d** [comment]
Ah, that's what you mean.

If you want to launch the export dialog UI, you have to [invoke the operator](https://pythonapi.upbge.org/bpy.ops.html):
bpy.ops.export_scene.selected('INVOKE_DEFAULT', exporter_str="export_scene.obj")
use_file_browser is True by default, so you can omit this argument.

If you want to export immediately (without opening the export dialog), you have to specify the filepath when executing the operator:
bpy.ops.export_scene.selected(filepath="some_folder/some_file.obj", exporter_str="export_scene.obj")
