### ISSUE TITLE
Feature request: screenshot thumbnail for the blend file

### ISSUE THREAD

**Issue by z01ks** [dairin0d/export-selected#6]
Hi! Thanks for this add-on. I am using it to build up my asset library by exporting selected objects from some of my scenes to separate blend files. However, I see that the default Blender feature of creating a thumbnail for every blend file is not implemented with this add-on. In fact, when I open one of the exported blends and hit Ctrl+S, there will be a thumbnail on the blend file next time. Would it be possible to generate the thumbnail from a screenshot at the moment of exporting? Thanks.

**Comment by dairin0d** [comment]
Thanks! This was due to saving .blend files as libraries. I switched to saving them as regular files by default, though the previous behavior can still be enabled in the user preferences (it allowed to avoid referencing unused libraries in the exported blends).

**Comment by z01ks** [comment]
Awesome. Thanks a lot!
