### ISSUE TITLE
no export  formats on 2.79.6

### ISSUE THREAD

**Issue by brothermechanic** [dairin0d/export-selected#9]
![screenshot_20181102_142533](https://user-images.githubusercontent.com/3109995/47912894-2a954680-deab-11e8-9312-86aca11ceeec.png)

**Comment by dairin0d** [comment]
Where did you download your 2.79.6 build? I tried to test this in the first one I could find (http://graphicall.org/1240 - Mantaflow Branch - 14/08/2018), but this problem doesn't occur there.

**Comment by brothermechanic** [comment]
This is my own (gentoo ebuild on python-3.6)

**Comment by dairin0d** [comment]
Thanks! Please check the latest version (committed a minute ago), it should be fixed now.

**Comment by brothermechanic** [comment]
You Are My Hero!
Thank you!

**Comment by dairin0d** [comment]
You're welcome :-)
